// Generated by gencpp from file modules/target_req.msg
// DO NOT EDIT!


#ifndef MODULES_MESSAGE_TARGET_REQ_H
#define MODULES_MESSAGE_TARGET_REQ_H

#include <ros/service_traits.h>


#include <modules/target_reqRequest.h>
#include <modules/target_reqResponse.h>


namespace modules
{

struct target_req
{

typedef target_reqRequest Request;
typedef target_reqResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct target_req
} // namespace modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::modules::target_req > {
  static const char* value()
  {
    return "ab16145b44c7b4e33fd358e08d9aef29";
  }

  static const char* value(const ::modules::target_req&) { return value(); }
};

template<>
struct DataType< ::modules::target_req > {
  static const char* value()
  {
    return "modules/target_req";
  }

  static const char* value(const ::modules::target_req&) { return value(); }
};


// service_traits::MD5Sum< ::modules::target_reqRequest> should match 
// service_traits::MD5Sum< ::modules::target_req > 
template<>
struct MD5Sum< ::modules::target_reqRequest>
{
  static const char* value()
  {
    return MD5Sum< ::modules::target_req >::value();
  }
  static const char* value(const ::modules::target_reqRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::modules::target_reqRequest> should match 
// service_traits::DataType< ::modules::target_req > 
template<>
struct DataType< ::modules::target_reqRequest>
{
  static const char* value()
  {
    return DataType< ::modules::target_req >::value();
  }
  static const char* value(const ::modules::target_reqRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::modules::target_reqResponse> should match 
// service_traits::MD5Sum< ::modules::target_req > 
template<>
struct MD5Sum< ::modules::target_reqResponse>
{
  static const char* value()
  {
    return MD5Sum< ::modules::target_req >::value();
  }
  static const char* value(const ::modules::target_reqResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::modules::target_reqResponse> should match 
// service_traits::DataType< ::modules::target_req > 
template<>
struct DataType< ::modules::target_reqResponse>
{
  static const char* value()
  {
    return DataType< ::modules::target_req >::value();
  }
  static const char* value(const ::modules::target_reqResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MODULES_MESSAGE_TARGET_REQ_H
