// Generated by gencpp from file modules/target_reqResponse.msg
// DO NOT EDIT!


#ifndef MODULES_MESSAGE_TARGET_REQRESPONSE_H
#define MODULES_MESSAGE_TARGET_REQRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace modules
{
template <class ContainerAllocator>
struct target_reqResponse_
{
  typedef target_reqResponse_<ContainerAllocator> Type;

  target_reqResponse_()
    : nav_point()
    , recon_type(0)  {
    }
  target_reqResponse_(const ContainerAllocator& _alloc)
    : nav_point(_alloc)
    , recon_type(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _nav_point_type;
  _nav_point_type nav_point;

   typedef int64_t _recon_type_type;
  _recon_type_type recon_type;




  typedef boost::shared_ptr< ::modules::target_reqResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::modules::target_reqResponse_<ContainerAllocator> const> ConstPtr;

}; // struct target_reqResponse_

typedef ::modules::target_reqResponse_<std::allocator<void> > target_reqResponse;

typedef boost::shared_ptr< ::modules::target_reqResponse > target_reqResponsePtr;
typedef boost::shared_ptr< ::modules::target_reqResponse const> target_reqResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::modules::target_reqResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::modules::target_reqResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace modules

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::modules::target_reqResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::modules::target_reqResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modules::target_reqResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modules::target_reqResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modules::target_reqResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modules::target_reqResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::modules::target_reqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9958aa1aaae7c968676532566b770ba6";
  }

  static const char* value(const ::modules::target_reqResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9958aa1aaae7c968ULL;
  static const uint64_t static_value2 = 0x676532566b770ba6ULL;
};

template<class ContainerAllocator>
struct DataType< ::modules::target_reqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "modules/target_reqResponse";
  }

  static const char* value(const ::modules::target_reqResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::modules::target_reqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose nav_point\n\
int64 recon_type\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::modules::target_reqResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::modules::target_reqResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nav_point);
      stream.next(m.recon_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct target_reqResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::modules::target_reqResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::modules::target_reqResponse_<ContainerAllocator>& v)
  {
    s << indent << "nav_point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.nav_point);
    s << indent << "recon_type: ";
    Printer<int64_t>::stream(s, indent + "  ", v.recon_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODULES_MESSAGE_TARGET_REQRESPONSE_H
